all : main date uptime cal

main : main.c 
		gcc main.c -o main

cal : cal.c 
		gcc cal.c -o cal
	
uptime: uptime.c 
		gcc uptime.c -o uptime 

date: date.c 
		gcc date.c -o date 

clean : 
		rm -r uptime cal date main


